### ISSUE TITLE
Error "moment undefined" on Node-WebKit

### ISSUE THREAD

**Issue by SoulOnFire** [urish/angular-moment#100] opened 2014-12-16 10:25 UTC
When we run the module inside node-webkit it throws a error of "moment undefined", because on initialisation we need to add one other else condition.
```javascript
if (typeof define === 'function' && define.amd) {
		define('angular-moment', ['angular', 'moment'], angularMoment);
	} else if (typeof module !== 'undefined' && module && module.exports) {
		angularMoment(angular, require('moment'));
	} else if(typeof global !== 'undefined') { //If inside Node-Webkit
          angularMoment(angular, require('moment'));
    }else{
		  angularMoment(angular, window.moment);
    }
```

**Comment by urish** [comment] 2015-01-12 08:05
@SoulOnFire which of the conditions in following `if` statement above does not hold true under node-webkit? 

`if (typeof module !== 'undefined' && module && module.exports)`

Thanks,
Uri

**Comment by RobeeeJay** [comment] 2015-01-21 13:15
Hi, this issue may not be specific to node-webkit, I've hit the same difficulty with browserify. The problem is the line:

angularMoment(angular, require('moment'));

This only works if you already included the moment.js with require("moment"), or can include it with that. If, for instance, you loaded it from another directory, or something like this:

window.moment = require("../../libs/moment/moment.min.js");

It will never be able to require that module, it's just not called the same as far as browserify is concerned. :/ I'm not sure what the best solution is, though the following works (it's a bit messy and far from ideal)...

	if (typeof define === 'function' && define.amd) {
		define('angular-moment', ['angular', 'moment'], angularMoment);
	} else if (!window.moment && typeof module !== 'undefined' && module && module.exports) {
		angularMoment(angular, require('moment'));
	} else {
		angularMoment(angular, window.moment);
	}

And add "moment" as an external in browserify.

**Comment by urish** [comment] 2015-01-21 13:49
@RobeeeJay Why would you want to require moment from a different source? 

If you install moment through NPM, then `require('moment')` should work for you...

**Comment by RobeeeJay** [comment] 2015-01-21 14:00
Not all build environments are clean and new, many have legacy requirements, you can't always just have a root directory with node_modules under it and install client side libraries with npm.

And not everyone installs client side libraries with npm (or bower). Some like to maintain a set of neat clean directories with the minimal files in them, and I like to keep libraries in the same repo as the application without all the build files.

Don't get me wrong, npm is great, browserify is great (node.js is great), but unless every single library you use is available on npm and works with browserify, it's never quite that simple.

**Comment by jagged3dge** [comment] 2015-07-17 10:06
Just hit this issue with `browserify` (with `watchify`) and `browserify-shim`. Here's how my `package.json` looks like (relevant parts):

```json
{
  "browser": {
    "jquery": "./bower_components/jquery/dist/jquery.min.js",
    "angular": "./bower_components/angular/angular.js",
    "moment": "./bower_components/moment/min/moment.min.js",
    "angular-moment": "./bower_components/angular-moment/angular-moment.js"
  },
  "browserify": {
    "transform": [
      "jadeify",
      "cssify",
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "jquery": {
      "exports": "jQuery"
    },
    "angular": {
      "exports": "angular",
      "depends": [
        "jquery"
      ]
    },
    "moment": "global:moment",
    "angular-moment": {
      "depends": ["moment:moment"],
      "exports": "angular.module('angularMoment').name"
    }
  }
}
```

And my `common.ui.dates` module:

```javascript
'use strict';
require('angular-moment');

var moduleName = 'common.ui.dates';

module.exports = function() {

    var angular = require('angular');
    var app = angular.module(moduleName, ['angularMoment']);

    require('./constants')(app);
    require('./directives')(app);
    require('./services')(app);

    return app;
};
```

Using this config, I'm still getting `Cannot find module 'moment'` on `browserify` build.
Has anyone found a workaround for using `angular-moment` with `browserify`?

**Comment by urish** [comment] 2015-09-15 10:19
Closing as there are several different issues in this thread, which may no longer be relevant for the current version. If any of them is still relevant as of 1.0.0-beta.1, please open a new issue for it.

Thanks!

**Closed by urish** 2015-09-15 10:19 UTC
