### ISSUE TITLE
angularMomentConfig.format does nothing?

### ISSUE THREAD

**Issue by nesler** [urish/angular-moment#211] opened 2015-12-07 12:28 UTC
HI,

I've tried setting the constant angularMomentConfig's format property, but it makes no difference. Looking through the source, it looks like it's never used? I'd love to get this to work, because I've got a load for date formatting to do, and id like to avoid specifying the date everywhere!

**Comment by miukki** [comment] 2015-12-07 17:45
yes i also wanna setup only ones data formatting..

**Comment by urish** [comment] 2015-12-07 21:15
Duplicate of #116

**Closed by urish** 2015-12-07 21:15 UTC
